# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  domain_name: example.com
  secret_key_base: e61354cf968ec3470c2646c5dffabd78e15c23fcd78d893f888d0a7781bd877afa5fe2f7469578930ab0c0d87a97eab6bbb2199c5000db6b9cbb448c97d7a641

test:
  secret_key_base: 2164e2ff5d8ce87dff95592db857ba140d15a46fb8188c6412d1b66accef53af1e58c07a18b06c29e2ee3287e900a1f765c23a7ecd4af94146025ea441368dd4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
